# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("Icon")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(10, 10, 1270, 631))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setLineWidth(4)
        self.mainFrame.setObjectName("mainFrame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1251, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.etapa1 = QtWidgets.QWidget()
        self.etapa1.setObjectName("etapa1")
        self.label_e1 = QtWidgets.QLabel(self.etapa1)
        self.label_e1.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        font.setUnderline(True)
        self.label_e1.setFont(font)
        self.label_e1.setObjectName("label_e1")
        self.tabPlots = QtWidgets.QTabWidget(self.etapa1)
        self.tabPlots.setGeometry(QtCore.QRect(490, 10, 751, 591))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabPlots.setFont(font)
        self.tabPlots.setObjectName("tabPlots")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotlayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotlayout_1.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_1.setObjectName("plotlayout_1")
        self.tabPlots.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plotlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plotlayout_2.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_2.setObjectName("plotlayout_2")
        self.tabPlots.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.plotlayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plotlayout_3.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_3.setObjectName("plotlayout_3")
        self.tabPlots.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.plotlayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.plotlayout_4.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_4.setObjectName("plotlayout_4")
        self.tabPlots.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.plotlayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.plotlayout_5.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_5.setObjectName("plotlayout_5")
        self.tabPlots.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.plotlayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.plotlayout_6.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_6.setObjectName("plotlayout_6")
        self.tabPlots.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.plotlayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.plotlayout_7.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_7.setObjectName("plotlayout_7")
        self.tabPlots.addTab(self.tab_7, "")
        self.formLayoutWidget = QtWidgets.QWidget(self.etapa1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 80, 472, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_tipo = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_tipo.setObjectName("label_tipo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_tipo)
        self.combo_tipo = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.combo_tipo.setFont(font)
        self.combo_tipo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combo_tipo.setObjectName("combo_tipo")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_tipo)
        self.label_aprox = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_aprox.setFont(font)
        self.label_aprox.setObjectName("label_aprox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_aprox)
        self.combo_aprox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.combo_aprox.setFont(font)
        self.combo_aprox.setObjectName("combo_aprox")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_aprox)
        self.label_denorm = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_denorm.setFont(font)
        self.label_denorm.setObjectName("label_denorm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_denorm)
        self.spin_denorm = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_denorm.setFont(font)
        self.spin_denorm.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_denorm.setMaximum(100)
        self.spin_denorm.setObjectName("spin_denorm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_denorm)
        self.label_minord = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_minord.setFont(font)
        self.label_minord.setObjectName("label_minord")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_minord)
        self.spin_minord = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_minord.setFont(font)
        self.spin_minord.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_minord.setMaximum(100)
        self.spin_minord.setObjectName("spin_minord")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_minord)
        self.label_maxord = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_maxord.setFont(font)
        self.label_maxord.setObjectName("label_maxord")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_maxord)
        self.spin_maxord = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_maxord.setFont(font)
        self.spin_maxord.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_maxord.setMaximum(100)
        self.spin_maxord.setProperty("value", 10)
        self.spin_maxord.setObjectName("spin_maxord")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_maxord)
        self.label_qmax = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_qmax.setFont(font)
        self.label_qmax.setObjectName("label_qmax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_qmax)
        self.spin_qmax = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_qmax.setFont(font)
        self.spin_qmax.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_qmax.setMaximum(100)
        self.spin_qmax.setProperty("value", 10)
        self.spin_qmax.setObjectName("spin_qmax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin_qmax)
        self.label_params = QtWidgets.QLabel(self.etapa1)
        self.label_params.setGeometry(QtCore.QRect(10, 40, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_params.setFont(font)
        self.label_params.setObjectName("label_params")
        self.label_plantilla = QtWidgets.QLabel(self.etapa1)
        self.label_plantilla.setGeometry(QtCore.QRect(10, 270, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_plantilla.setFont(font)
        self.label_plantilla.setObjectName("label_plantilla")
        self.btn_plot = QtWidgets.QPushButton(self.etapa1)
        self.btn_plot.setGeometry(QtCore.QRect(140, 560, 221, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.btn_plot.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_plot.setFont(font)
        self.btn_plot.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_plot.setObjectName("btn_plot")
        self.plantilla_box = QtWidgets.QStackedWidget(self.etapa1)
        self.plantilla_box.setGeometry(QtCore.QRect(10, 310, 471, 241))
        self.plantilla_box.setObjectName("plantilla_box")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.page_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 471, 241))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setHorizontalSpacing(20)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_Ap = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_Ap.setFont(font)
        self.label_Ap.setObjectName("label_Ap")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Ap)
        self.spin_Ap = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_Ap.setFont(font)
        self.spin_Ap.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_Ap.setDecimals(3)
        self.spin_Ap.setMinimum(-300.0)
        self.spin_Ap.setMaximum(300.0)
        self.spin_Ap.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_Ap.setProperty("value", 1.0)
        self.spin_Ap.setObjectName("spin_Ap")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_Ap)
        self.label_Aa = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_Aa.setFont(font)
        self.label_Aa.setObjectName("label_Aa")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Aa)
        self.spin_Aa = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_Aa.setFont(font)
        self.spin_Aa.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_Aa.setDecimals(3)
        self.spin_Aa.setMinimum(-300.0)
        self.spin_Aa.setMaximum(300.0)
        self.spin_Aa.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_Aa.setProperty("value", 1.0)
        self.spin_Aa.setObjectName("spin_Aa")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_Aa)
        self.label_wp = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wp.setFont(font)
        self.label_wp.setObjectName("label_wp")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_wp)
        self.spin_wp = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wp.setFont(font)
        self.spin_wp.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wp.setDecimals(3)
        self.spin_wp.setMaximum(1000000000.0)
        self.spin_wp.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wp.setProperty("value", 1.0)
        self.spin_wp.setObjectName("spin_wp")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_wp)
        self.label_wp_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wp_2.setFont(font)
        self.label_wp_2.setObjectName("label_wp_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_wp_2)
        self.label_wa_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wa_2.setFont(font)
        self.label_wa_2.setObjectName("label_wa_2")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_wa_2)
        self.spin_wa_2 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wa_2.setFont(font)
        self.spin_wa_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wa_2.setDecimals(3)
        self.spin_wa_2.setMaximum(1000000000.0)
        self.spin_wa_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wa_2.setProperty("value", 1.0)
        self.spin_wa_2.setObjectName("spin_wa_2")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spin_wa_2)
        self.label_check_plantilla_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_check_plantilla_3.setFont(font)
        self.label_check_plantilla_3.setObjectName("label_check_plantilla_3")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_check_plantilla_3)
        self.check_plantilla = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_plantilla.sizePolicy().hasHeightForWidth())
        self.check_plantilla.setSizePolicy(sizePolicy)
        self.check_plantilla.setSizeIncrement(QtCore.QSize(0, 0))
        self.check_plantilla.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.check_plantilla.setFont(font)
        self.check_plantilla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_plantilla.setAutoFillBackground(False)
        self.check_plantilla.setStyleSheet("")
        self.check_plantilla.setText("")
        self.check_plantilla.setIconSize(QtCore.QSize(16, 16))
        self.check_plantilla.setChecked(True)
        self.check_plantilla.setObjectName("check_plantilla")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.check_plantilla)
        self.label_wa = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wa.setFont(font)
        self.label_wa.setObjectName("label_wa")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_wa)
        self.spin_wp_2 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wp_2.setFont(font)
        self.spin_wp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wp_2.setDecimals(3)
        self.spin_wp_2.setMaximum(1000000000.0)
        self.spin_wp_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wp_2.setProperty("value", 1.0)
        self.spin_wp_2.setObjectName("spin_wp_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_wp_2)
        self.spin_wa = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wa.setFont(font)
        self.spin_wa.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wa.setDecimals(3)
        self.spin_wa.setMaximum(1000000000.0)
        self.spin_wa.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wa.setProperty("value", 1.0)
        self.spin_wa.setObjectName("spin_wa")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin_wa)
        self.label_ripple = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_ripple.setFont(font)
        self.label_ripple.setObjectName("label_ripple")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_ripple)
        self.spin_ripple = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_ripple.setFont(font)
        self.spin_ripple.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_ripple.setDecimals(3)
        self.spin_ripple.setMinimum(0.0)
        self.spin_ripple.setMaximum(300.0)
        self.spin_ripple.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_ripple.setProperty("value", 1.0)
        self.spin_ripple.setObjectName("spin_ripple")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_ripple)
        self.plantilla_box.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.page_4)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(0, 20, 471, 131))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_8.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setHorizontalSpacing(20)
        self.formLayout_8.setVerticalSpacing(6)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_tau = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_tau.setFont(font)
        self.label_tau.setObjectName("label_tau")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_tau)
        self.label_wrg = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wrg.setFont(font)
        self.label_wrg.setObjectName("label_wrg")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_wrg)
        self.GD_wrg = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.GD_wrg.setFont(font)
        self.GD_wrg.setAlignment(QtCore.Qt.AlignCenter)
        self.GD_wrg.setDecimals(3)
        self.GD_wrg.setMaximum(1000000000.0)
        self.GD_wrg.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.GD_wrg.setProperty("value", 1.0)
        self.GD_wrg.setObjectName("GD_wrg")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.GD_wrg)
        self.label_gamma = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_gamma.setFont(font)
        self.label_gamma.setObjectName("label_gamma")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_gamma)
        self.label_check_plantilla_4 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_check_plantilla_4.setFont(font)
        self.label_check_plantilla_4.setObjectName("label_check_plantilla_4")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_check_plantilla_4)
        self.check_plantilla_GD = QtWidgets.QCheckBox(self.formLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_plantilla_GD.sizePolicy().hasHeightForWidth())
        self.check_plantilla_GD.setSizePolicy(sizePolicy)
        self.check_plantilla_GD.setSizeIncrement(QtCore.QSize(0, 0))
        self.check_plantilla_GD.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.check_plantilla_GD.setFont(font)
        self.check_plantilla_GD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_plantilla_GD.setAutoFillBackground(False)
        self.check_plantilla_GD.setStyleSheet("")
        self.check_plantilla_GD.setText("")
        self.check_plantilla_GD.setIconSize(QtCore.QSize(16, 16))
        self.check_plantilla_GD.setChecked(True)
        self.check_plantilla_GD.setObjectName("check_plantilla_GD")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.check_plantilla_GD)
        self.GD_tau = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.GD_tau.setFont(font)
        self.GD_tau.setAlignment(QtCore.Qt.AlignCenter)
        self.GD_tau.setDecimals(3)
        self.GD_tau.setMinimum(0.0)
        self.GD_tau.setMaximum(100.0)
        self.GD_tau.setSingleStep(0.001)
        self.GD_tau.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.GD_tau.setProperty("value", 1.0)
        self.GD_tau.setObjectName("GD_tau")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.GD_tau)
        self.GD_gamma = QtWidgets.QSpinBox(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.GD_gamma.setFont(font)
        self.GD_gamma.setAlignment(QtCore.Qt.AlignCenter)
        self.GD_gamma.setMaximum(100)
        self.GD_gamma.setObjectName("GD_gamma")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.GD_gamma)
        self.plantilla_box.addWidget(self.page_4)
        self.label_e1.raise_()
        self.tabPlots.raise_()
        self.formLayoutWidget.raise_()
        self.label_params.raise_()
        self.label_plantilla.raise_()
        self.plantilla_box.raise_()
        self.btn_plot.raise_()
        self.stackedWidget.addWidget(self.etapa1)
        self.etapa2 = QtWidgets.QWidget()
        self.etapa2.setObjectName("etapa2")
        self.label_e2 = QtWidgets.QLabel(self.etapa2)
        self.label_e2.setGeometry(QtCore.QRect(10, 0, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        font.setUnderline(True)
        self.label_e2.setFont(font)
        self.label_e2.setObjectName("label_e2")
        self.stage_list = QtWidgets.QListWidget(self.etapa2)
        self.stage_list.setGeometry(QtCore.QRect(10, 210, 371, 341))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.stage_list.setFont(font)
        self.stage_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stage_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stage_list.setStyleSheet("QListWidget::item { \n"
"    border-bottom: 1px solid  rgb(200, 200, 200);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: black;\n"
"}")
        self.stage_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.stage_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.stage_list.setObjectName("stage_list")
        self.label_stage_list = QtWidgets.QLabel(self.etapa2)
        self.label_stage_list.setGeometry(QtCore.QRect(10, 50, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_stage_list.setFont(font)
        self.label_stage_list.setObjectName("label_stage_list")
        self.btn_new_stage = QtWidgets.QPushButton(self.etapa2)
        self.btn_new_stage.setGeometry(QtCore.QRect(310, 130, 71, 61))
        self.btn_new_stage.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_new_stage.setObjectName("btn_new_stage")
        self.btn_delete_stage = QtWidgets.QPushButton(self.etapa2)
        self.btn_delete_stage.setGeometry(QtCore.QRect(280, 560, 101, 41))
        self.btn_delete_stage.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_delete_stage.setObjectName("btn_delete_stage")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.etapa2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 141, 65))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.combo_polo1 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.combo_polo1.setObjectName("combo_polo1")
        self.combo_polo1.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_polo1)
        self.label_polo2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_polo2.setFont(font)
        self.label_polo2.setObjectName("label_polo2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_polo2)
        self.combo_polo2 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.combo_polo2.setObjectName("combo_polo2")
        self.combo_polo2.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_polo2)
        self.label_polo1 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_polo1.setFont(font)
        self.label_polo1.setObjectName("label_polo1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_polo1)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.etapa2)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(160, 130, 141, 65))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setHorizontalSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_cero1 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_cero1.setFont(font)
        self.label_cero1.setObjectName("label_cero1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_cero1)
        self.combo_cero1 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.combo_cero1.setObjectName("combo_cero1")
        self.combo_cero1.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_cero1)
        self.label_cero2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_cero2.setFont(font)
        self.label_cero2.setObjectName("label_cero2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_cero2)
        self.combo_cero2 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.combo_cero2.setObjectName("combo_cero2")
        self.combo_cero2.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_cero2)
        self.btn_edit_stage = QtWidgets.QPushButton(self.etapa2)
        self.btn_edit_stage.setGeometry(QtCore.QRect(10, 560, 101, 41))
        self.btn_edit_stage.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_edit_stage.setObjectName("btn_edit_stage")
        self.tabPlots_2 = QtWidgets.QTabWidget(self.etapa2)
        self.tabPlots_2.setGeometry(QtCore.QRect(400, 10, 841, 591))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabPlots_2.setFont(font)
        self.tabPlots_2.setObjectName("tabPlots_2")
        self.tab2_1 = QtWidgets.QWidget()
        self.tab2_1.setObjectName("tab2_1")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.tab2_1)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 841, 561))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.plotlayout2_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.plotlayout2_1.setContentsMargins(0, 0, 0, 0)
        self.plotlayout2_1.setObjectName("plotlayout2_1")
        self.tabPlots_2.addTab(self.tab2_1, "")
        self.tab2_2 = QtWidgets.QWidget()
        self.tab2_2.setObjectName("tab2_2")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.tab2_2)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 841, 561))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.plotlayout2_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.plotlayout2_2.setContentsMargins(0, 0, 0, 0)
        self.plotlayout2_2.setObjectName("plotlayout2_2")
        self.tabPlots_2.addTab(self.tab2_2, "")
        self.tab2_3 = QtWidgets.QWidget()
        self.tab2_3.setObjectName("tab2_3")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.tab2_3)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, 841, 561))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.plotlayout2_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.plotlayout2_3.setContentsMargins(0, 0, 0, 0)
        self.plotlayout2_3.setObjectName("plotlayout2_3")
        self.tabPlots_2.addTab(self.tab2_3, "")
        self.btn_plot_stage = QtWidgets.QPushButton(self.etapa2)
        self.btn_plot_stage.setGeometry(QtCore.QRect(140, 560, 111, 41))
        self.btn_plot_stage.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_plot_stage.setObjectName("btn_plot_stage")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.etapa2)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 90, 221, 31))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setHorizontalSpacing(10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_gain = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_gain.setFont(font)
        self.label_gain.setObjectName("label_gain")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_gain)
        self.spin_gain = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_gain.setFont(font)
        self.spin_gain.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_gain.setDecimals(3)
        self.spin_gain.setMinimum(-300.0)
        self.spin_gain.setMaximum(300.0)
        self.spin_gain.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_gain.setProperty("value", 0.0)
        self.spin_gain.setObjectName("spin_gain")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_gain)
        self.label_gain_total = QtWidgets.QLabel(self.etapa2)
        self.label_gain_total.setGeometry(QtCore.QRect(240, 92, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_gain_total.setFont(font)
        self.label_gain_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gain_total.setObjectName("label_gain_total")
        self.stackedWidget.addWidget(self.etapa2)
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(1150, 650, 121, 41))
        self.btn_next.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_next.setObjectName("btn_next")
        self.btn_prev = QtWidgets.QPushButton(self.centralwidget)
        self.btn_prev.setGeometry(QtCore.QRect(1020, 650, 121, 41))
        self.btn_prev.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_prev.setObjectName("btn_prev")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(10, 650, 121, 41))
        self.btn_open.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_open.setObjectName("btn_open")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(150, 650, 121, 41))
        self.btn_save.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_save.setObjectName("btn_save")
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setGeometry(QtCore.QRect(290, 650, 171, 41))
        self.btn_export.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_export.setObjectName("btn_export")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabPlots.setCurrentIndex(0)
        self.plantilla_box.setCurrentIndex(0)
        self.tabPlots_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filter Design Tool"))
        self.label_e1.setText(_translate("MainWindow", "Etapa 1"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_1), _translate("MainWindow", "Atenuación"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_2), _translate("MainWindow", "Fase"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_3), _translate("MainWindow", "Retardo de Grupo"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_4), _translate("MainWindow", "Polos y Ceros"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_5), _translate("MainWindow", "Impulso"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_6), _translate("MainWindow", "Escalón"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_7), _translate("MainWindow", "Máximo Q"))
        self.label_tipo.setText(_translate("MainWindow", "Tipo de Filtro"))
        self.combo_tipo.setItemText(0, _translate("MainWindow", "Pasa Bajos"))
        self.combo_tipo.setItemText(1, _translate("MainWindow", "Pasa Altos"))
        self.combo_tipo.setItemText(2, _translate("MainWindow", "Pasa Banda"))
        self.combo_tipo.setItemText(3, _translate("MainWindow", "Rechaza Banda"))
        self.combo_tipo.setItemText(4, _translate("MainWindow", "Retardo de Grupo"))
        self.label_aprox.setText(_translate("MainWindow", "Aproximación"))
        self.combo_aprox.setItemText(0, _translate("MainWindow", "Butterworth"))
        self.combo_aprox.setItemText(1, _translate("MainWindow", "Chebyshev I"))
        self.combo_aprox.setItemText(2, _translate("MainWindow", "Chebyshev II"))
        self.combo_aprox.setItemText(3, _translate("MainWindow", "Cauer"))
        self.combo_aprox.setItemText(4, _translate("MainWindow", "Legendre"))
        self.combo_aprox.setItemText(5, _translate("MainWindow", "Bessel"))
        self.combo_aprox.setItemText(6, _translate("MainWindow", "Gauss"))
        self.label_denorm.setText(_translate("MainWindow", "Rango de Desnormalización"))
        self.label_minord.setText(_translate("MainWindow", "Orden Mínimo"))
        self.label_maxord.setText(_translate("MainWindow", "Orden Máximo"))
        self.label_qmax.setText(_translate("MainWindow", "Q  Máximo"))
        self.label_params.setText(_translate("MainWindow", "Parámetros:"))
        self.label_plantilla.setText(_translate("MainWindow", "Plantilla:"))
        self.btn_plot.setText(_translate("MainWindow", "Graficar"))
        self.label_Ap.setText(_translate("MainWindow", "Banda de paso (Ap)"))
        self.label_Aa.setText(_translate("MainWindow", "Banda de atenuación (Aa)    "))
        self.label_wp.setText(_translate("MainWindow", "Frecuencia ωp"))
        self.label_wp_2.setText(_translate("MainWindow", "Frecuencia ωp-"))
        self.label_wa_2.setText(_translate("MainWindow", "Frecuencia ωa-"))
        self.label_check_plantilla_3.setText(_translate("MainWindow", "Visualizar Plantilla"))
        self.label_wa.setText(_translate("MainWindow", "Frecuencia ωa"))
        self.label_ripple.setText(_translate("MainWindow", "Máximo Ripple"))
        self.label_tau.setText(_translate("MainWindow", "Retardo en banda de paso (𝜏(0))"))
        self.label_wrg.setText(_translate("MainWindow", "Frecuencia ωRG"))
        self.label_gamma.setText(_translate("MainWindow", "Error maximo de retardo en ωRG (𝛾%)"))
        self.label_check_plantilla_4.setText(_translate("MainWindow", "Visualizar Plantilla"))
        self.label_e2.setText(_translate("MainWindow", "Etapa 2"))
        self.label_stage_list.setText(_translate("MainWindow", "Lista de Etapas:"))
        self.btn_new_stage.setText(_translate("MainWindow", "Crear"))
        self.btn_delete_stage.setText(_translate("MainWindow", "Borrar"))
        self.combo_polo1.setItemText(0, _translate("MainWindow", "-"))
        self.label_polo2.setText(_translate("MainWindow", "Polo B:"))
        self.combo_polo2.setItemText(0, _translate("MainWindow", "-"))
        self.label_polo1.setText(_translate("MainWindow", "Polo A:"))
        self.label_cero1.setText(_translate("MainWindow", "Cero A:"))
        self.combo_cero1.setItemText(0, _translate("MainWindow", "-"))
        self.label_cero2.setText(_translate("MainWindow", "Cero B:"))
        self.combo_cero2.setItemText(0, _translate("MainWindow", "-"))
        self.btn_edit_stage.setText(_translate("MainWindow", "Editar"))
        self.tabPlots_2.setTabText(self.tabPlots_2.indexOf(self.tab2_1), _translate("MainWindow", "Polos y Ceros"))
        self.tabPlots_2.setTabText(self.tabPlots_2.indexOf(self.tab2_2), _translate("MainWindow", "Respuesta en Frecuencia Total"))
        self.tabPlots_2.setTabText(self.tabPlots_2.indexOf(self.tab2_3), _translate("MainWindow", "Respuesta en Frecuencia de la Etapa"))
        self.btn_plot_stage.setText(_translate("MainWindow", "Graficar"))
        self.label_gain.setText(_translate("MainWindow", "Ganancia:"))
        self.label_gain_total.setText(_translate("MainWindow", "Restante: 0.000 dB"))
        self.btn_next.setText(_translate("MainWindow", "Siguiente"))
        self.btn_prev.setText(_translate("MainWindow", "Anterior"))
        self.btn_open.setText(_translate("MainWindow", "Abrir"))
        self.btn_save.setText(_translate("MainWindow", "Guardar"))
        self.btn_export.setText(_translate("MainWindow", "Exportar PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
