# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("Icon")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(10, 10, 1181, 611))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setLineWidth(4)
        self.mainFrame.setObjectName("mainFrame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1161, 591))
        self.stackedWidget.setObjectName("stackedWidget")
        self.etapa1 = QtWidgets.QWidget()
        self.etapa1.setObjectName("etapa1")
        self.label_e1 = QtWidgets.QLabel(self.etapa1)
        self.label_e1.setGeometry(QtCore.QRect(10, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        font.setUnderline(True)
        self.label_e1.setFont(font)
        self.label_e1.setObjectName("label_e1")
        self.tabPlots = QtWidgets.QTabWidget(self.etapa1)
        self.tabPlots.setGeometry(QtCore.QRect(410, 0, 751, 591))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabPlots.setFont(font)
        self.tabPlots.setObjectName("tabPlots")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotlayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotlayout_1.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_1.setObjectName("plotlayout_1")
        self.tabPlots.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plotlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plotlayout_2.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_2.setObjectName("plotlayout_2")
        self.tabPlots.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.plotlayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plotlayout_3.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_3.setObjectName("plotlayout_3")
        self.tabPlots.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.plotlayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.plotlayout_4.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_4.setObjectName("plotlayout_4")
        self.tabPlots.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.plotlayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.plotlayout_5.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_5.setObjectName("plotlayout_5")
        self.tabPlots.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.plotlayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.plotlayout_6.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_6.setObjectName("plotlayout_6")
        self.tabPlots.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_7)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 751, 561))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.plotlayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.plotlayout_7.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_7.setObjectName("plotlayout_7")
        self.tabPlots.addTab(self.tab_7, "")
        self.formLayoutWidget = QtWidgets.QWidget(self.etapa1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 90, 381, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_tipo = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_tipo.setObjectName("label_tipo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_tipo)
        self.combo_tipo = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.combo_tipo.setFont(font)
        self.combo_tipo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combo_tipo.setObjectName("combo_tipo")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_tipo)
        self.label_aprox = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_aprox.setFont(font)
        self.label_aprox.setObjectName("label_aprox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_aprox)
        self.combo_aprox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.combo_aprox.setFont(font)
        self.combo_aprox.setObjectName("combo_aprox")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.combo_aprox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_aprox)
        self.label_desnorm = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_desnorm.setFont(font)
        self.label_desnorm.setObjectName("label_desnorm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_desnorm)
        self.spin_desnom = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_desnom.setFont(font)
        self.spin_desnom.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_desnom.setMaximum(100)
        self.spin_desnom.setObjectName("spin_desnom")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_desnom)
        self.label_minord = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_minord.setFont(font)
        self.label_minord.setObjectName("label_minord")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_minord)
        self.spin_minord = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_minord.setFont(font)
        self.spin_minord.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_minord.setMaximum(100)
        self.spin_minord.setObjectName("spin_minord")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_minord)
        self.label_maxord = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_maxord.setFont(font)
        self.label_maxord.setObjectName("label_maxord")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_maxord)
        self.spin_maxord = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_maxord.setFont(font)
        self.spin_maxord.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_maxord.setMaximum(100)
        self.spin_maxord.setObjectName("spin_maxord")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_maxord)
        self.label_qmax = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_qmax.setFont(font)
        self.label_qmax.setObjectName("label_qmax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_qmax)
        self.spin_qmax = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_qmax.setFont(font)
        self.spin_qmax.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_qmax.setMaximum(100)
        self.spin_qmax.setObjectName("spin_qmax")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin_qmax)
        self.label_params = QtWidgets.QLabel(self.etapa1)
        self.label_params.setGeometry(QtCore.QRect(10, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_params.setFont(font)
        self.label_params.setObjectName("label_params")
        self.label_plantilla = QtWidgets.QLabel(self.etapa1)
        self.label_plantilla.setGeometry(QtCore.QRect(10, 290, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_plantilla.setFont(font)
        self.label_plantilla.setObjectName("label_plantilla")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.etapa1)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 330, 385, 197))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_Ap = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_Ap.setFont(font)
        self.label_Ap.setObjectName("label_Ap")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Ap)
        self.label_Aa = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_Aa.setFont(font)
        self.label_Aa.setObjectName("label_Aa")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Aa)
        self.label_wp = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wp.setFont(font)
        self.label_wp.setObjectName("label_wp")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_wp)
        self.label_wa = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wa.setFont(font)
        self.label_wa.setObjectName("label_wa")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_wa)
        self.spin_Ap = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_Ap.setFont(font)
        self.spin_Ap.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_Ap.setDecimals(10)
        self.spin_Ap.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_Ap.setProperty("value", 0.0)
        self.spin_Ap.setObjectName("spin_Ap")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_Ap)
        self.spin_Aa = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_Aa.setFont(font)
        self.spin_Aa.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_Aa.setDecimals(10)
        self.spin_Aa.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_Aa.setProperty("value", 0.0)
        self.spin_Aa.setObjectName("spin_Aa")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_Aa)
        self.spin_wp = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wp.setFont(font)
        self.spin_wp.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wp.setDecimals(10)
        self.spin_wp.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wp.setProperty("value", 0.0)
        self.spin_wp.setObjectName("spin_wp")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_wp)
        self.spin_wa = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wa.setFont(font)
        self.spin_wa.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wa.setDecimals(10)
        self.spin_wa.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wa.setProperty("value", 0.0)
        self.spin_wa.setObjectName("spin_wa")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_wa)
        self.label_wo = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_wo.setFont(font)
        self.label_wo.setObjectName("label_wo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_wo)
        self.spin_wo = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.spin_wo.setFont(font)
        self.spin_wo.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_wo.setDecimals(10)
        self.spin_wo.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spin_wo.setProperty("value", 0.0)
        self.spin_wo.setObjectName("spin_wo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_wo)
        self.check_plantilla = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_plantilla.sizePolicy().hasHeightForWidth())
        self.check_plantilla.setSizePolicy(sizePolicy)
        self.check_plantilla.setSizeIncrement(QtCore.QSize(0, 0))
        self.check_plantilla.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.check_plantilla.setFont(font)
        self.check_plantilla.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_plantilla.setAutoFillBackground(False)
        self.check_plantilla.setStyleSheet("")
        self.check_plantilla.setText("")
        self.check_plantilla.setIconSize(QtCore.QSize(16, 16))
        self.check_plantilla.setChecked(True)
        self.check_plantilla.setObjectName("check_plantilla")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.check_plantilla)
        self.label_check_plantilla = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_check_plantilla.setFont(font)
        self.label_check_plantilla.setObjectName("label_check_plantilla")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_check_plantilla)
        self.btn_plot = QtWidgets.QPushButton(self.etapa1)
        self.btn_plot.setGeometry(QtCore.QRect(100, 530, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.btn_plot.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_plot.setFont(font)
        self.btn_plot.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_plot.setObjectName("btn_plot")
        self.stackedWidget.addWidget(self.etapa1)
        self.etapa2 = QtWidgets.QWidget()
        self.etapa2.setObjectName("etapa2")
        self.label_e2 = QtWidgets.QLabel(self.etapa2)
        self.label_e2.setGeometry(QtCore.QRect(10, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        font.setUnderline(True)
        self.label_e2.setFont(font)
        self.label_e2.setObjectName("label_e2")
        self.stage_list = QtWidgets.QListWidget(self.etapa2)
        self.stage_list.setGeometry(QtCore.QRect(10, 120, 121, 291))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.stage_list.setFont(font)
        self.stage_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stage_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.stage_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.stage_list.setObjectName("stage_list")
        self.label_stage_list = QtWidgets.QLabel(self.etapa2)
        self.label_stage_list.setGeometry(QtCore.QRect(10, 60, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_stage_list.setFont(font)
        self.label_stage_list.setObjectName("label_stage_list")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.etapa2)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(150, 40, 1011, 551))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.plotlayout_poles = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.plotlayout_poles.setContentsMargins(0, 0, 0, 0)
        self.plotlayout_poles.setObjectName("plotlayout_poles")
        self.label_diagrama = QtWidgets.QLabel(self.etapa2)
        self.label_diagrama.setGeometry(QtCore.QRect(220, 10, 941, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_diagrama.setFont(font)
        self.label_diagrama.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diagrama.setObjectName("label_diagrama")
        self.btn_new_stage = QtWidgets.QPushButton(self.etapa2)
        self.btn_new_stage.setGeometry(QtCore.QRect(10, 490, 121, 41))
        self.btn_new_stage.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_new_stage.setObjectName("btn_new_stage")
        self.btn_delete_stage = QtWidgets.QPushButton(self.etapa2)
        self.btn_delete_stage.setGeometry(QtCore.QRect(10, 540, 121, 41))
        self.btn_delete_stage.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_delete_stage.setObjectName("btn_delete_stage")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.etapa2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 420, 121, 61))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_polo1 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_polo1.setFont(font)
        self.label_polo1.setObjectName("label_polo1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_polo1)
        self.combo_polo1 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.combo_polo1.setObjectName("combo_polo1")
        self.combo_polo1.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_polo1)
        self.label_polo2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_polo2.setFont(font)
        self.label_polo2.setObjectName("label_polo2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_polo2)
        self.combo_polo2 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.combo_polo2.setObjectName("combo_polo2")
        self.combo_polo2.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_polo2)
        self.stackedWidget.addWidget(self.etapa2)
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(1060, 630, 121, 41))
        self.btn_next.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_next.setObjectName("btn_next")
        self.btn_prev = QtWidgets.QPushButton(self.centralwidget)
        self.btn_prev.setGeometry(QtCore.QRect(930, 630, 121, 41))
        self.btn_prev.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_prev.setObjectName("btn_prev")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(10, 630, 121, 41))
        self.btn_open.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_open.setObjectName("btn_open")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(140, 630, 121, 41))
        self.btn_save.setStyleSheet("QPushButton {\n"
" background-color: rgb(240, 240, 240);\n"
" border-style: outset;\n"
" border-width: 5px;\n"
" border-radius: 10px;\n"
" border-color: gray;\n"
" font: Rockwell;\n"
" font-size: 24px;\n"
" }\n"
" QPushButton:pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" border-style: inset;\n"
" }\n"
" QPushButton:hover:!pressed {\n"
" background-color: rgb(220, 220, 220);\n"
" }\n"
"")
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabPlots.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filter Design Tool"))
        self.label_e1.setText(_translate("MainWindow", "Etapa 1"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_1), _translate("MainWindow", "Atenuación"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_2), _translate("MainWindow", "Fase"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_3), _translate("MainWindow", "Retardo de Grupo"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_4), _translate("MainWindow", "Polos y Ceros"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_5), _translate("MainWindow", "Impulso"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_6), _translate("MainWindow", "Escalón"))
        self.tabPlots.setTabText(self.tabPlots.indexOf(self.tab_7), _translate("MainWindow", "Máximo Q"))
        self.label_tipo.setText(_translate("MainWindow", "Tipo de Filtro"))
        self.combo_tipo.setItemText(0, _translate("MainWindow", "Pasa Bajos"))
        self.combo_tipo.setItemText(1, _translate("MainWindow", "Pasa Altos"))
        self.combo_tipo.setItemText(2, _translate("MainWindow", "Pasa Banda"))
        self.combo_tipo.setItemText(3, _translate("MainWindow", "Rechaza Banda"))
        self.combo_tipo.setItemText(4, _translate("MainWindow", "Retardo de Grupo"))
        self.label_aprox.setText(_translate("MainWindow", "Aproximación"))
        self.combo_aprox.setItemText(0, _translate("MainWindow", "Butterworth"))
        self.combo_aprox.setItemText(1, _translate("MainWindow", "Chebyshev I"))
        self.combo_aprox.setItemText(2, _translate("MainWindow", "Chebyshev II"))
        self.combo_aprox.setItemText(3, _translate("MainWindow", "Bessel"))
        self.combo_aprox.setItemText(4, _translate("MainWindow", "Cauer"))
        self.combo_aprox.setItemText(5, _translate("MainWindow", "Legendre"))
        self.combo_aprox.setItemText(6, _translate("MainWindow", "Gauss"))
        self.label_desnorm.setText(_translate("MainWindow", "Rango de Desnormalización"))
        self.label_minord.setText(_translate("MainWindow", "Orden Mínimo"))
        self.label_maxord.setText(_translate("MainWindow", "Orden Máximo"))
        self.label_qmax.setText(_translate("MainWindow", "Q  Máximo"))
        self.label_params.setText(_translate("MainWindow", "Parámetros:"))
        self.label_plantilla.setText(_translate("MainWindow", "Plantilla:"))
        self.label_Ap.setText(_translate("MainWindow", "Banda de paso (Ap)"))
        self.label_Aa.setText(_translate("MainWindow", "Banda de atenuación (Aa)    "))
        self.label_wp.setText(_translate("MainWindow", "Frecuencia ωp"))
        self.label_wa.setText(_translate("MainWindow", "Frecuencia ωa"))
        self.label_wo.setText(_translate("MainWindow", "Frecuencia ωo"))
        self.label_check_plantilla.setText(_translate("MainWindow", "Visualizar Plantilla"))
        self.btn_plot.setText(_translate("MainWindow", "Graficar"))
        self.label_e2.setText(_translate("MainWindow", "Etapa 2"))
        self.label_stage_list.setText(_translate("MainWindow", "Lista de\n"
"Etapas:"))
        self.label_diagrama.setText(_translate("MainWindow", "Diagrama de Polos y Ceros"))
        self.btn_new_stage.setText(_translate("MainWindow", "Crear"))
        self.btn_delete_stage.setText(_translate("MainWindow", "Borrar"))
        self.label_polo1.setText(_translate("MainWindow", "Polo 1:"))
        self.combo_polo1.setItemText(0, _translate("MainWindow", "-"))
        self.label_polo2.setText(_translate("MainWindow", "Polo 2:"))
        self.combo_polo2.setItemText(0, _translate("MainWindow", "-"))
        self.btn_next.setText(_translate("MainWindow", "Siguiente"))
        self.btn_prev.setText(_translate("MainWindow", "Anterior"))
        self.btn_open.setText(_translate("MainWindow", "Abrir"))
        self.btn_save.setText(_translate("MainWindow", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
